### ISSUE TITLE
could your README get a little more info/description ?

### ISSUE THREAD

**Issue by bmullan** [janxb/ContainerConfigWrappers#1]
The README doesn't really tell a potential user much about your project.  I'd be interested in knowing more myself.

**Comment by janxb** [comment]
Sorry for the late response. I have updated the README. If you have additional questions, feel free to ask! :)

**Comment by bmullan** [comment]
You title just says ContainerConfigWrappers

Today the word "Container" can mean

web containers
docker containers
lxd/lxc containers
etc

maybe specify which of those it is referring to as all are different technologies.
